//import 'semantic-ui-css/semantic.css';
//import 'semantic-ui-css/semantic.js';

import 'semantic-ui-css/components/site.css';
import 'semantic-ui-css/components/site.js';

import 'semantic-ui-css/components/accordion.css'
import 'semantic-ui-css/components/api.js'
import 'semantic-ui-css/components/breadcrumb.css';
import 'semantic-ui-css/components/button.css'
import 'semantic-ui-css/components/checkbox.js';
import 'semantic-ui-css/components/checkbox.css';
import 'semantic-ui-css/components/container.css';
import 'semantic-ui-css/components/dimmer.css';
import 'semantic-ui-css/components/dimmer.js';
import 'semantic-ui-css/components/divider.css';
import 'semantic-ui-css/components/dropdown.css';
import 'semantic-ui-css/components/dropdown.js';
import 'semantic-ui-css/components/feed.css';
import 'semantic-ui-css/components/form.js';
import 'semantic-ui-css/components/form.css';
import 'semantic-ui-css/components/grid';
import 'semantic-ui-css/components/header.css';
import 'semantic-ui-css/components/icon.css';
import 'semantic-ui-css/components/input.css';
import 'semantic-ui-css/components/item.css';
import 'semantic-ui-css/components/image.css';
import 'semantic-ui-css/components/label.css';
import 'semantic-ui-css/components/list.css';
import 'semantic-ui-css/components/loader.css';
import 'semantic-ui-css/components/menu.css';
import 'semantic-ui-css/components/message.css';
import 'semantic-ui-css/components/modal.js';
import 'semantic-ui-css/components/modal.css';
import 'semantic-ui-css/components/popup.css';
import 'semantic-ui-css/components/popup.js';
import 'semantic-ui-css/components/progress.css';
import 'semantic-ui-css/components/reset.css';
import 'semantic-ui-css/components/segment.css';
import 'semantic-ui-css/components/search.js';
import 'semantic-ui-css/components/search.css';
import 'semantic-ui-css/components/sidebar.css';
import 'semantic-ui-css/components/tab.css';
import 'semantic-ui-css/components/tab.js';
import 'semantic-ui-css/components/table.css';
import 'semantic-ui-css/components/transition.css';
import 'semantic-ui-css/components/transition.js';
